### ISSUE TITLE
New Release for AndroidX update

### ISSUE THREAD

**Issue by dsuresh-ap** [takahirom/Hyperion-Simple-Item#11]
Is it possible to publish a new release with the AndroidX changes?

**Comment by maxfie1d** [comment]
+1

**Comment by shyvum** [comment]
@takahirom, is it possible to give this a quick shot? this is the only dependency (apart from 400 others) on our project, due to which we have to keep jetifier on. would appreciate.

**Comment by shyvum** [comment]
@takahirom just saw it was merged in https://github.com/takahirom/Hyperion-Simple-Item/pull/10 but never reached a version. Possible to publish one quickly from master?

**Comment by takahirom** [comment]
I made a tag. Does it work for you?

**Comment by shyvum** [comment]
yes, works. thanks!
